Chill\ActivityBundle\Entity\ActivityReason:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: json_array
        active:
            type: boolean
    manyToOne:
        category:
            targetEntity: Chill\ActivityBundle\Entity\ActivityReasonCategory
    lifecycleCallbacks: {  }