services:
   - chill/database:latest
 
before_script:
   - export GITHUB_COMPOSER_AUTH=$GITHUB_TOKEN
   - composer install --no-interaction
   - cp Test/Fixtures/App/app/config/parameters.gitlab-ci.yml Test/Fixtures/App/app/config/parameters.yml
#   - php Test/Fixtures/App/app/console --env=test cache:warmup
   - php Test/Fixtures/App/app/console doctrine:migrations:migrate --env=test --no-interaction
   - php Test/Fixtures/App/app/console doctrine:fixtures:load --env=test --no-interaction

test:php-5.6:
   stage: test
   script: phpunit --testdox
test:php-7:
   stage: test
   script: phpunit --testdox
